version: '3.8'

services:
  node-app:
    build:
      context: ./app
    expose:
      - "3000"
    environment:
      - PORT=3000

    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    depends_on:
      - node-app
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
